# dockerfile
FROM node:16-alpine

# create app dir
WORKDIR /usr/src/app

# copy package.json & package.lock.json
COPY package*.json ./

# bundle src
COPY . .

# install typescript compiler 
RUN npm install tsc

# compile and build
RUN npm run build

# map port 
EXPOSE 5000

# start server ($ node server.js)
CMD ["node", "dist/server.js"]